# Generated by Django 5.0.6 on 2024-06-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
