# Generated by Django 5.0.6 on 2024-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_featured_alter_event_city_alter_event_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.CharField(max_length=100),
        ),
    ]
