# Generated by Django 5.0.6 on 2024-06-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_city_alter_event_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_tickets',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
